### PR TITLE
Following the TSWG process migrates license to OWFa 1.0

### PR DESCRIPTION
**Pull request by m00sey**

### CODE REVIEW

**Comment by swcurran** [comment]
Isn’t a an open specification license different from an open source software license? E.g. that both should apply, covering the specification and any open source code that happens to be in the repo?  That is what is done in the Community Specification License v1.0.

**Comment by m00sey** [comment]
My understanding was the software aspect had moved to hyperledger, we have an additional LICENSE.md that addressed other contributions in the the keri stack of repos, would you feel better off this was also included?

https://github.com/trustoverip/tswg-acdc-specification/blob/main/LICENSE.md

**Comment by swcurran** [comment]
I don’t know exactly what the OWF is and why it matters, but I think it is a Very Bad idea to change any open source software license from Apache 2.0 to something else. It will cause grief.

I like the other summary better (the link in your comment), but I would change the first paragraph to:

> All specifications in this repository are Copyright 2023 ACDC Contributors and all contributions to this repository are Licensed under the OWFa 1.0 (the "License") [here](https://github.com/trustoverip/tswg-acdc-specification/blob/main/LICENSE).
> 
> All software in this repository are Copyright 2023 ACDC Contributors and all contributions to this repository are Licensed under the Apache 2.0 [link to file with license in the repo].`

**Comment by m00sey** [comment]
Apologies for the confusion @swcurran I thought this would be a formality.

The TSWG opted to recharter and adopt OWFa 1.0 for Copyright/Patent modes, we previously had Creative Commons Attribution 4.0/W3C and retained Apache 2.0 for software, given this repo exists for the specification and the implementation is in hyper ledger I wasn't foreseeing any issues.

The TSWG went through a 60 day notice period of the change in accordance with recharging under the JDF.

**Comment by swcurran** [comment]
Agree — this should be an admin task my suggestions are more at the ToIP level than at this group and so am happy to let this issue go.  If ToIP leadership says this is the right thing to do, go for it.

**Review by 2byrds — APPROVED** [review]
LGTM

**Pull request merged**
