### PR TITLE
Linkable normative_references.md

### PR DESCRIPTION
**Pull request by 2byrds**
We have broken links and variety of links all over the spec docs, some of which have aged out, etc. This PR starts the process of consolidating normative reference links to one easy to maintain and reference section.

### CODE REVIEW

**Review by daidoji — COMMENTED** [review]
Maybe its an open issue in those repos to get the same landing page but the IPEX, OOBI, and SAID links all look like

image

**Comment by 2byrds** [comment]
> Maybe its an open issue in those repos to get the same landing page but the IPEX, OOBI, and SAID links all look like
> 
> image

yes good point. i wasn't sure what to do at this point. I believe those are all getting merged into the KERI spec.... maybe i should just remove them and lean on the KERI spec. Thoughts?

**Comment by 2byrds** [comment]
@m00sey helped me:
SAID is in CESR spec now https://trustoverip.github.io/tswg-cesr-specification/#self-addressing-identifier-said
IPEX is in ACDC spec now https://trustoverip.github.io/tswg-acdc-specification/#issuance-and-presentation-exchange-ipex
OOBI is in KERI spec now https://trustoverip.github.io/tswg-keri-specification/#out-of-band-introduction-oobi
I'll update the PR now @daidoji

**Comment by 2byrds** [comment]
> @m00sey helped me: SAID is in CESR spec now https://trustoverip.github.io/tswg-cesr-specification/#self-addressing-identifier-said IPEX is in ACDC spec now https://trustoverip.github.io/tswg-acdc-specification/#issuance-and-presentation-exchange-ipex OOBI is in KERI spec now https://trustoverip.github.io/tswg-keri-specification/#out-of-band-introduction-oobi I'll update the PR now @daidoji

okay i've updated the PR @daidoji and after this one, i'll update the appendix/terminology to link to the proper spec (for SAID, OOBI, and IPEX)

**Review by daidoji — APPROVED** [review]
+1

**Pull request merged**
