### PR TITLE
Use JsonWebKey for verification methods, optional support for CesrKey

### PR DESCRIPTION
**Pull request by peacekeeper**
This replaces PRs https://github.com/trustoverip/tswg-did-method-webs-specification/pull/31, https://github.com/trustoverip/tswg-did-method-webs-specification/pull/32, https://github.com/trustoverip/tswg-did-method-webs-specification/pull/33, and https://github.com/trustoverip/tswg-did-method-webs-specification/pull/34.

This says the DID method uses the `JsonWebKey` verification method type by default for Ed25519 and secp256k1.

But it also adds support for a `CesrKey` verification method type via the `transformKeys` DID parameter than can be optionally used by clients, e.g. with a DID URL like this:

`did:webs:example.com:Ew-o5dU5WjDrxDBK4b4HrF82_rYb6MX6xsegjq4n0Y7M?transformKeys=CesrKey`

Fixes https://github.com/trustoverip/tswg-did-method-webs-specification/issues/12

### CODE REVIEW

**Comment by peacekeeper** [comment]
Multi-sig and thresholds will be addressed in a separate PR after this one, see issue https://github.com/trustoverip/tswg-did-method-webs-specification/issues/8.

**Comment by 2byrds** [comment]
> Multi-sig and thresholds will be addressed in a separate PR after this one, see issue #8.

Would it be simpler to make CesrKey the default, then address more familiar formats that don't support multisig, etc. Meaning we are on solid ground if we do CesrKey, then it can take as long as necessary to address the issues with more limited key types.

I'd like to know what is lost if we start with CesrKey as a default, since it fully supports all of our requirements.

**Comment by peacekeeper** [comment]
> I'd like to discuss inverting the default to CesrKey

Yes happy to discuss that, I agree it would have advantages, insofar as we would full preserve all the KERI key types, etc.

> what is lost if we start with CesrKey as a default

The main downside would be interoperability. Virtually no other DID-based application or service would know how to use CesrKey, since we just invented that. Yes they could then use the DID parameter transformKeys=JsonWebKey, but to my knowledge not many DID applications support that either.

> caveats about lacking multisig

I think there is a way of expressing KERI style multisig with the non-CESR-based approach described in https://github.com/trustoverip/tswg-did-method-webs-specification/issues/8, but I have yet to try it out and write a PR for that.

**Comment by swcurran** [comment]
We can discuss tomorrow, but I think that we would significantly reduce the likelihood of DID Method acceptance if we create a brand new mechanism for something that is already widely available in order to add a feature (multi-sig) that, while being potentially useful, has few use cases.  I’m all for mentioning it in the spec as optional, and if feasible, putting it in the implementation, but the primary should be immediately recognizable.

That opens the door for innovators, but our goal with this DID method is mainstream.  Let’s not kill it with tomorrow’s possibilities.

**Comment by dhh1128** [comment]
I think I'm in favor of having JsonWebKey be the default, and having CESR be possible. It's uglier for KERI people, but I think it's politically expedient.

**Comment by 2byrds** [comment]
> I think I'm in favor of having JsonWebKey be the default, and having CESR be possible. It's uglier for KERI people, but I think it's politically expedient.

@dhh1128, @peacekeeper and I spoke more on this yesterday. IF multisig can be properly expressed using ConditionalProofs and JsonWebKey then that makes JsonWebKey (for me) worth discussing as a default. @peacekeeper is looking into that and has a PR about it that we both have approved. I look forward to hearing what he's learned, etc. If we can't properly express multi-sig using them, then I think we need to find another default. Apparently its rare for DID-world users to use transformKeys and I worry that in a predominately multi-sig world (like organizational identity) that did:webs could become problematic. Part of my reservation is that I don't know how a client detects they need to use transformKey for a multi-sig AID.

**Review by 2byrds — APPROVED** [review]
LGTM per our meeting

**Comment by peacekeeper** [comment]
Thanks @2byrds , maybe you can merge this if you think it's ready.

**Pull request merged**
