### PR TITLE
Docs/support IPs

### PR DESCRIPTION
**Pull request by 2byrds**
#98

### CODE REVIEW

**Comment by swcurran** [comment]
I don't like this change, as it introduces an incompatibility with `did:web` and (IMHO) is only for edge cases.  I'm not going to make a big deal about it if others really want it. As such, I'll leave others to approve it (or not).

**Comment by 2byrds** [comment]
> I don't like this change, as it introduces an incompatibility with `did:web` and (IMHO) is only for edge cases. I'm not going to make a big deal about it if others really want it. As such, I'll leave others to approve it (or not).

That is a valid criticism. I remain flexible depending on how others feel about going beyond did:web.

**Review by dhh1128 — APPROVED** [review]
I am in favor of this change.

The incompatibility that Stephen highlights is not with any did:web values that do now or ever could exist. Rather, it is with did:webs values that are used in cases where did:web would never make sense. Thus, we introduce zero friction in moving from did:web to did:webs, and zero friction in moving back, *if the did:webs is published in a place where a did:web could exist.* If the the did:webs is published in a place where a did:web could not exist, then no user of did:web will care. Whether this is a corner case or not depends on whether you think the web is only a publication site for servers. It is, today -- but I'm not sure it will remain that way as IPv6 becomes popular.

**Comment by daidoji** [comment]
I think I'm for this change and the IP thing stood out to me originally too.

`did:web` probably had that constraint because their security model is tied to the TLS cert and they specify that the domain name be the **FQDN** (although this is mentioned in passing so its easy to miss)?. I think of weird historical oddities like https://cabforum.org/guidance-ip-addresses-certificates/ , that discourage the use of IP addresses in the cert because of how legacy PKI systems handled them weirdly.  I think a lot of CAs still won't write you a cert with an IP address by default because of stuff like this.

I agree with deviating from the did:web spec per @dhh1128's rationale above.  Without our method's security context being tied to the TLS certificate explicitly, we probably don't need to worry about what the did:web spec authors were worrying about imo when they made that constraint.

**Comment by daidoji** [comment]
Also if we're going to allow IP addresses this change should probably be larger in this section specifying an _FQDN or IP address_ everywhere we currently specify FQDN currently.

**Comment by 2byrds** [comment]
> Also if we're going to allow IP addresses this change should probably be larger in this section specifying an _FQDN or IP address_ everywhere we currently specify FQDN currently.

@daidoji great point. would the term 'host' be okay? i could add it to the terminology so that hoverover says 'fully qualified domain name or IP address'

**Comment by daidoji** [comment]
@2byrds `host` seems reasonable to me.  `authority` is what chat-gpt says about something that could be an IP but also a domain but that might be too weird for easy understanding.

**Comment by 2byrds** [comment]
> @2byrds `host` seems reasonable to me. `authority` is what chat-gpt says about something that could be an IP but also a domain but that might be too weird for easy understanding.

PR updated to use generalize to the term `host`

**Pull request merged**
